"""FastAPI entrypoint for the AI orchestrator.

Endpoints:
- `GET /health` — liveness.
- `POST /ai/stream` — SSE-streamed LLM response. Pulls live snapshot +
  constraints + RAG, calls LiteLLM with `stream=True`, yields chunks to the
  candidate, and mirrors each chunk to the realtime telemetry channel so
  the interviewer console sees them in real time.
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import AsyncIterator
from datetime import UTC, datetime

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from litellm import acompletion
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse

from .clients import (
    broadcast_chunk,
    fetch_constraints,
    fetch_snapshot,
    list_sandbox_files,
)
from .config import get_settings
from .prompt import build_messages
from .rag import fetch_relevant_chunks

log = logging.getLogger("bleucent.ai")
logging.basicConfig(level=logging.INFO)


app = FastAPI(title="Bleucent AI Orchestrator", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class StreamRequest(BaseModel):
    interview_id: str = Field(..., description="UUID of the interview.")
    prompt_id: str = Field(..., description="UUID generated by the candidate's browser.")
    prompt: str = Field(..., min_length=1, max_length=8000)
    actor: str = Field("candidate", pattern="^(candidate|interviewer)$")
    sandbox_id: str | None = None


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/ai/stream")
async def ai_stream(req: StreamRequest):
    """SSE: each event has `data: {"chunk": "..."}` with a final `[DONE]`."""

    snapshot, constraints, sandbox_files, chunks = await asyncio.gather(
        fetch_snapshot(req.interview_id),
        fetch_constraints(req.interview_id),
        list_sandbox_files(req.sandbox_id),
        fetch_relevant_chunks(req.interview_id, req.prompt),
    )

    messages = build_messages(
        snapshot=snapshot,
        constraints=constraints,
        chunks=chunks,
        sandbox_files=sandbox_files,
        prompt=req.prompt,
    )

    # Mirror the prompt itself once. We keep it short — the orchestrator is
    # the only place that knows the AI is about to respond.
    asyncio.create_task(
        broadcast_chunk(
            req.interview_id,
            kind="ai_prompt",
            actor=req.actor,
            payload={
                "promptId": req.prompt_id,
                "prompt": req.prompt,
            },
        )
    )

    async def event_source() -> AsyncIterator[dict[str, str]]:
        s = get_settings()
        try:
            response = await acompletion(
                model=s.litellm_default_model,
                messages=messages,
                stream=True,
                temperature=0.2,
            )
        except Exception as exc:
            log.exception("LLM call failed")
            yield {"event": "error", "data": f'{{"error": "{exc}"}}'}
            return

        try:
            async for chunk in response:
                delta = ""
                try:
                    delta = chunk.choices[0].delta.content or ""
                except (AttributeError, IndexError, KeyError):
                    delta = ""
                if not delta:
                    continue
                # Fire-and-forget mirror so latency to the candidate stays low.
                asyncio.create_task(
                    broadcast_chunk(
                        req.interview_id,
                        kind="ai_response_chunk",
                        actor="ai",
                        payload={
                            "promptId": req.prompt_id,
                            "chunk": delta,
                            "done": False,
                        },
                    )
                )
                yield {
                    "event": "message",
                    "data": _json({"chunk": delta}),
                }
        finally:
            # Signal completion to both candidate and the interviewer console.
            asyncio.create_task(
                broadcast_chunk(
                    req.interview_id,
                    kind="ai_response_chunk",
                    actor="ai",
                    payload={
                        "promptId": req.prompt_id,
                        "chunk": "",
                        "done": True,
                    },
                )
            )
            yield {"event": "message", "data": "[DONE]"}

    return EventSourceResponse(
        event_source(),
        headers={
            "X-Bleucent-Stream-Started": datetime.now(UTC).isoformat(),
        },
    )


def _json(obj: dict) -> str:
    import json

    return json.dumps(obj, separators=(",", ":"))
